car_service/account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path('staff/', views.StaffPageView.as_view(), name='staff'),
    path('staff-forms/', views.StaffPageFormsView.as_view(), name='staff-forms'),
    path('staff-lifts/', views.StaffPageLiftsView.as_view(), name='staff-lifts'),
    path('staff-profile/', views.StaffPageProfileView.as_view(), name='staff-profile'),
    path('profile/', views.UserPageView.as_view(), name='user'),
    path('login/', views.login_user, name='login'),
    path('register/', views.registration_user, name='register'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('activate/<uidb64>/<token>', views.confirm_user, name='activate')
]

car_service/api/urls.py
from django.urls import path
from api import views

app_name = 'api'
urlpatterns = [
    path('check_status/', views.check_status_car, name='check_status'),
    path('make_recording/', views.make_recording, name='make_recording'),
    path('get_free_place/', views.get_free_place, name='get_free_place'),
    path('get_custom_service/', views.get_custom_service, name='get_custom_service'),
    path('get_events/', views.get_events, name='get_events'),
    path('change_event/', views.change_event, name='change_event'),
    path('get_select_event/', views.get_select_event, name='get_select_event'),
    path('get_working_conditions/', views.get_working_conditions, name='get_working_conditions'),
    path('clean_working_conditions/', views.clean_working_conditions, name='clean_working_conditions'),
    path('delete-event/', views.delete_event, name='delete_event'),
    path('change_personal_data', views.change_personal_data, name='change-personal-data'),
    path('add_car/', views.add_car, name='add_car'),
    path('delete-car/', views.delete_car, name='delete_car'),
    path('change_car_info/', views.change_car_info, name='change_car_info'),
]

car_service/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('site_service.urls')),
    path('account/', include('account.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +\
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

car_service/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" {% block class-html %}{% endblock class-html %}>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link type="image/x-icon" href="{% static 'img/favicon/favicon.ico' %}" rel="shortcut icon">
    <link type="Image/x-icon" href="{% static 'img/favicon/favicon.ico' %}" rel="icon">

    <title> {% block title %}Автосервис{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
    {% block style %}{% endblock style %}
</head>
<body>
{% block header %}
    <header class="header">
        <div class="container">
            <div class="header__info">
                <a href="{% url 'home_page' %}">
                    <div class="header__logo">

                        <img src="{{ headers.logo.url }}" alt="ART-KAT">
                        <div class="header__text">
                            <p class="header__name">{{ headers.logo_text_first|default_if_none:"ART-KAT"}}</p>
                            <p class="header__desc">{{ headers.logo_text_second|default_if_none:"ART-KAT"}}</p>
                        </div>
                    </div>
                </a>
                <ul class="header__menu menu">
                    <li class="menu__item">
                        <a href="#step-scroll">Как мы работаем?</a>
                    </li>
                    <li class="menu__item">
                        <a href="#list-services-scroll">Наши услуги</a>
                    </li>
                    <li class="menu__item">
                        <a href="#advantages-scroll">Преимущества</a>
                    </li>
                    <li class="menu__item">
                        <a href="#team-scroll">Наша команда</a>
                    </li>
                    <li class="menu__item">
                        <a href="#rewievs-scroll">Отзывы</a>
                    </li>
                </ul>
                <ul class="menu__media">
                    <li class="menu__item">
                        <a href="#step-scroll">Как мы работаем?</a>
                    </li>
                    <li class="menu__item">
                        <a href="#list-services-scroll">Наши услуги</a>
                    </li>
                    <li class="menu__item">
                        <a href="#advantages-scroll">Преимущества</a>
                    </li>
                    <li class="menu__item">
                        <a href="#team-scroll">Наша команда</a>
                    </li>
                    <li class="menu__item">
                        <a href="#rewievs-scroll">Отзывы</a>
                    </li>
                </ul>
                {% block account-login %}

                    {% if user.is_admin %}
                        <div class="header__auth--good">
                            <a href="/admin"><span>Управление</span> <img src="{% static 'img/header/login.svg' %}"
                                                                          alt="->"></a>
                        </div>
                    {% elif user.is_staff %}
                        <div class="header__auth--good">
                            <a href="{% url 'account:staff' %}"><span>Администратор</span> <img
                                    src="{% static 'img/header/login.svg' %}" alt="->"></a>
                        </div>
                    {% elif user.is_authenticated %}
                        <div class="header__auth--good">
                            <a href="{% url 'account:user' %}"><span>{{ user.email }}</span> <img
                                    src="{% static 'img/header/login.svg' %}" alt="->"></a>
                        </div>
                    {% else %}
                        <div class="header__auth">
                            <span>Войти</span> <img src="{% static 'img/header/login.svg' %}" alt="->">
                        </div>
                    {% endif %}
                    <div class="header__media">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                {% endblock account-login %}
            </div>
        </div>
    </header>
{% endblock header %}
{% block content %}{% endblock content %}
<script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
<script src="https://unpkg.com/imask"></script>
<script src="{% static 'js/base.js' %}"></script>
{% block script %}{% endblock script %}

</body>
</html>